프로젝트 구성안 README.md 파일 추가
wookikiik/angular_study pull request #16
Opened 2021-02-09 06:47 UTC by basestar011

- 기능 목록
- 페이지 구성
- Backend API / Response / Model 정보
- Package 구성

2021-02-09 07:05 UTC, wookikiik requested changes

2021-02-09 07:05 UTC, wookikiik commented on projects/han/README.md
> +  - 전시된 도시를 클릭하여 도시 날씨 전시 페이지로 이동
도시 날씨 전시 페이지  => 도시 별 날씨 페이지 

* 명칭을 통일 해야 찾기 쉬움

2021-02-09 07:05 UTC, wookikiik commented on projects/han/README.md
> +    created: string;
created 용도는??

2021-02-09 07:05 UTC, wookikiik commented on projects/han/README.md
> +    - weather.guard.ts : 날씨 페이지 guard
역할 사용 설명 필요 
페이지 구성에서는 아래와 같은 기능이 있는데 역할이 무엇인지 모르겠음
=> _검색을 하지 않은 경우 검색 페이지로 이동하는 버튼 전시_

2021-02-15 02:32 UTC, wookikiik requested changes

2021-02-15 02:32 UTC, wookikiik commented on projects/han/README.md
> +- 도시 별 날씨 페이지( /weather )
메인페이지 내용 추가 =

2021-02-15 02:39 UTC, basestar011 commented on projects/han/README.md
> +  - 전시된 도시를 클릭하여 도시 날씨 전시 페이지로 이동
수정하겠습니다

2021-02-15 02:39 UTC, basestar011 commented on projects/han/README.md
> +    created: string;
사용되지 않을 property 로, 삭제하겠습니다.

2021-02-15 03:11 UTC, basestar011 commented on projects/han/README.md
> +    - weather.guard.ts : 날씨 페이지 guard
최초 사이트 접근 시 전시되는 메인 페이지를 추가하여, 도시 검색을 하지 않은 경우에는 메인 페이지로, 도시 검색 후에는 도시 별 날씨 페이지로 이동하도록 수정할 예정입니다.

2021-02-15 03:12 UTC, basestar011 commented on projects/han/README.md
> +- 도시 별 날씨 페이지( /weather )
잘못된 검색 후 도시 별 날씨 페이지로 이동하거나, 검색을 하지 않았을 때 전시되는 메인 페이지를 추가하겠습니다.

2021-02-16 05:02 UTC, closed without merging